'use client';

import { motion } from 'framer-motion';
import { useRef } from 'react';
import gsap from 'gsap';
import { useGSAP } from '@gsap/react';
import ParallaxImage from '@/components/ui/ParallaxImage';

const testimonials = [
  {
    quote: "Eco Architect AI reduced our planning phase by 60%. The satellite analysis and generative zoning maps were incredibly accurate.",
    name: 'Sarah Jenkins',
    role: 'City Planner — Seattle',
    avatar: '/images/portrait_2.jpg',
    position: 'top-[8%] left-[28%]',
  },
  {
    quote: "The flood resilience models generated by the platform were instrumental in securing approval for our infrastructure upgrade.",
    name: 'Michael Torres',
    role: 'Civil Engineer — Miami',
    avatar: '/images/portrait_1.jpg',
    position: 'top-[30%] right-[4%]',
  },
  {
    quote: "A game changer for smart city development. We can now visualize and iterate on massive masterplans in days instead of months.",
    name: 'Elena Rostova',
    role: 'Chief Architect — Global Firm',
    avatar: '/images/portrait_3.jpg',
    position: 'bottom-[12%] left-[6%]',
  },
];

// TestimonialsMarquee — mirrors Doorly screenshot 8:
// Giant "CLIENT STORIES" background wordmark + full-bleed photo + 
// floating dark quote cards staggered across the section
export default function TestimonialsMarquee() {
  const containerRef = useRef<HTMLDivElement>(null);
  const textRef = useRef<HTMLParagraphElement>(null);

  useGSAP(() => {
    if (!containerRef.current || !textRef.current) return;
    
    gsap.to(textRef.current, {
      x: '-30%',
      ease: 'none',
      scrollTrigger: {
        trigger: containerRef.current,
        start: 'top bottom',
        end: 'bottom top',
        scrub: true,
      }
    });
  }, { scope: containerRef });

  return (
    <section
      ref={containerRef}
      className="relative w-full overflow-hidden"
      style={{ minHeight: '90vh' }}
      aria-labelledby="stories-heading"
    >
      {/* Full-bleed background photo with parallax */}
      <div className="absolute inset-0">
        <ParallaxImage
          src="/images/exterior_villa.jpg"
          alt="Aerial view of award-winning architecture with infinity pool and mountain landscape"
          className="w-full h-full object-cover"
          scale={1.2}
          speed={0.5}
        />
        <div className="absolute inset-0 bg-black/40 pointer-events-none" />
      </div>

      {/* Giant background wordmark "CLIENT STORIES" — matches screenshot 8 */}
      <div
        className="absolute inset-0 flex items-center pointer-events-none select-none overflow-hidden"
        aria-hidden="true"
      >
        <p
          ref={textRef}
          className="font-display font-black text-white/15 uppercase whitespace-nowrap"
          style={{
            fontSize: 'clamp(6rem, 18vw, 22rem)',
            lineHeight: 0.85,
            letterSpacing: '-0.03em',
            paddingLeft: '50vw', // Start partially offscreen
          }}
        >
          &nbsp;SUCCESS STORIES&nbsp;&nbsp;SUCCESS STORIES&nbsp;&nbsp;SUCCESS STORIES&nbsp;
        </p>
      </div>

      {/* Section heading */}
      <h2 id="stories-heading" className="sr-only">Client Stories</h2>

      {/* Floating testimonial cards */}
      <div className="relative z-10 w-full h-full min-h-[90vh]">
        {testimonials.map((t, i) => (
          <motion.div
            key={t.name}
            className={`absolute max-w-xs bg-[#1a1a1a]/90 backdrop-blur-sm p-7 ${t.position}`}
            initial={{ opacity: 0, y: 30 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ delay: i * 0.18, duration: 0.8, ease: [0.16, 1, 0.3, 1] }}
            style={{ 
              position: 'absolute',
              top: ['10%', '35%', 'auto'][i],
              bottom: i === 2 ? '10%' : 'auto',
              left: i === 0 ? '25%' : i === 2 ? '5%' : 'auto',
              right: i === 1 ? '5%' : 'auto',
            }}
          >
            {/* Quote mark */}
            <p className="text-accent text-4xl font-display leading-none mb-4">"</p>
            <p className="text-white text-sm leading-relaxed mb-6">
              {t.quote}
            </p>
            {/* Author */}
            <div className="flex items-center gap-3">
              <img
                src={t.avatar}
                alt={`Portrait of ${t.name}`}
                className="w-10 h-10 rounded-full object-cover"
              />
              <div>
                <p className="text-white font-semibold text-sm">{t.name}</p>
                <p className="text-white/50 text-xs">{t.role}</p>
              </div>
            </div>
          </motion.div>
        ))}
      </div>

      {/* Spacer so cards have room */}
      <div className="relative z-0 min-h-[90vh]" />
    </section>
  );
}
